# Generated by Django 3.2 on 2021-05-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmsslider',
            name='cms_text',
            field=models.TextField(default='default title', max_length=200, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='cmsslider',
            name='cms_img',
            field=models.ImageField(upload_to='sliderimg/'),
        ),
    ]
