# Generated by Django 3.2 on 2021-05-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20210523_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmsslider',
            name='cms_css',
            field=models.CharField(max_length=200, null=True, verbose_name='Css класс'),
        ),
        migrations.AlterField(
            model_name='cmsslider',
            name='cms_text',
            field=models.TextField(default='-', max_length=200, verbose_name='Текст'),
        ),
    ]
