# Generated by Django 3.2 on 2021-06-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_comentcrm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statuscrm',
            old_name='Status_name',
            new_name='status_name',
        ),
        migrations.AlterField(
            model_name='comentcrm',
            name='coment_text',
            field=models.TextField(verbose_name='Текст комментария'),
        ),
    ]
